### ISSUE TITLE
Studentクラスの属性を変更お願いします

### ISSUE THREAD

**Issue by takattty** [takattty/ruby31-rails70-devcontainer-for-git#5]
# 背景
DBで年齢のデータ型を数値から文字列に変更する方針になったからです。

## 対応内容
- Studentクラスの年齢の型を文字列へ変更してください
- ついでにTeacherクラスの年齢の方も文字列へ変更お願いします。

**Comment by hayato-f** [comment]
先にTeacherクラスの年齢の型変更を行いました。
Studentクラスの年齢の型は、変更次第UPします！！

**Comment by hayato-f** [comment]
# Studentクラス、Teacherクラスの年齢の型を変更しました。
## 確認してほしいこと
- student モデルの年齢の型
- teacher モデルの年齢の型
